export const SET_ADD_PROJECT_FIELDS = "SET_ADD_PROJECT_FIELDS";
export const CLOSE_CONFIRM_MODAL = "CLOSE_CONFIRM_MODAL";
export const ADD_PROJECT = "ADD_PROJECT";
export const SET_REMOVABLE_PROJECT_ID = "SET_REMOVABLE_PROJECT_ID";
export const REMOVE_SINGLE_PROJECT = "REMOVE_SINGLE_PROJECT";
export const SET_EDITABLE_PROJECT = "SET_EDITABLE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const SET_PROJECT_DETAIL = "SET_PROJECT_DETAIL";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

